\set ON_ERROR_STOP on
BEGIN;
SELECT plan(1);

DO E'DECLARE\n  table_name text;\nBEGIN\n  FOREACH table_name IN ARRAY ARRAY[\n    ''offer_markets'', ''offer_merchants'', ''offer_stores'', ''offer_brands'',\n    ''offer_products'', ''offer_product_variants'', ''offer_packages'', ''offer_sources'',\n    ''offer_ingestion_runs'', ''offer_raw_observations'', ''offer_parser_incidents'',\n    ''offer_offers'', ''offer_price_history'', ''offer_match_reviews''\n  ]\n  LOOP\n    IF NOT EXISTS (\n      SELECT 1 FROM pg_class c\n      JOIN pg_namespace n ON n.oid = c.relnamespace\n      WHERE n.nspname = ''public'' AND c.relname = table_name AND c.relrowsecurity\n    ) THEN\n      RAISE EXCEPTION ''RLS is not enabled for %'', table_name;\n    END IF;\n  END LOOP;\nEND;';

DO E'BEGIN\n  IF has_table_privilege(''anon'', ''public.offer_raw_observations'', ''SELECT'')\n    OR has_table_privilege(''anon'', ''public.offer_offers'', ''INSERT'')\n    OR has_table_privilege(''authenticated'', ''public.offer_sources'', ''SELECT'')\n  THEN\n    RAISE EXCEPTION ''browser roles received Offer Finder table privileges'';\n  END IF;\n\n  IF NOT has_function_privilege(\n    ''anon'',\n    ''public.offer_search_v1(text,text,text,text,uuid,boolean,integer,timestamptz,uuid)'',\n    ''EXECUTE''\n  ) THEN\n    RAISE EXCEPTION ''safe public search function is not executable'';\n  END IF;\nEND;';

DO E'DECLARE\n  v_market_id uuid := gen_random_uuid();\n  v_merchant_id uuid := gen_random_uuid();\n  v_source_id uuid := gen_random_uuid();\n  v_run_id uuid := gen_random_uuid();\n  v_observation_id uuid := gen_random_uuid();\nBEGIN\n  INSERT INTO public.offer_markets\n    (id, code, country_code, default_currency, locale, timezone)\n  VALUES (v_market_id, ''RU'', ''RU'', ''RUB'', ''ru-RU'', ''Europe/Moscow'')\n  ON CONFLICT (code) DO UPDATE SET code = EXCLUDED.code\n  RETURNING id INTO v_market_id;\n  INSERT INTO public.offer_merchants (id, market_id, name, slug)\n  VALUES (v_merchant_id, v_market_id, ''Fixture merchant'', ''fixture-merchant'');\n  INSERT INTO public.offer_sources\n    (id, merchant_id, name, adapter_key, adapter_version, source_type,\n     approved_origins, approved_fetch_origins)\n  VALUES (\n    v_source_id, v_merchant_id, ''Fixture source'', ''fixture'', ''1.0.0'', ''manual_file'',\n    ''["https://fixture.invalid"]''::jsonb, ''["https://fixture.invalid"]''::jsonb\n  );\n  INSERT INTO public.offer_ingestion_runs\n    (id, source_id, trigger, status, adapter_version, started_at)\n  VALUES (v_run_id, v_source_id, ''manual'', ''running'', ''1.0.0'', clock_timestamp());\n  INSERT INTO public.offer_raw_observations\n    (id, run_id, source_id, external_offer_id, source_url_hash, observation_hash,\n     payload_json, collected_at, parser_version)\n  VALUES (\n    v_observation_id, v_run_id, v_source_id, ''external-1'', repeat(''a'', 64), repeat(''b'', 64),\n    ''{"price":1299}''::jsonb, clock_timestamp(), ''1.0.0''\n  );\n\n  INSERT INTO public.offer_raw_observations\n    (run_id, source_id, external_offer_id, source_url_hash, observation_hash,\n     payload_json, collected_at, parser_version)\n  VALUES (\n    v_run_id, v_source_id, ''external-1'', repeat(''a'', 64), repeat(''b'', 64),\n    ''{"price":1299}''::jsonb, clock_timestamp(), ''1.0.0''\n  )\n  ON CONFLICT (source_id, external_offer_id, observation_hash) DO NOTHING;\n\n  IF (SELECT count(*) FROM public.offer_raw_observations\n      WHERE source_id = v_source_id AND external_offer_id = ''external-1'') <> 1 THEN\n    RAISE EXCEPTION ''raw observation import is not idempotent'';\n  END IF;\n\n  BEGIN\n    UPDATE public.offer_raw_observations\n    SET payload_json = ''{"price":1}''::jsonb\n    WHERE id = v_observation_id;\n    RAISE EXCEPTION ''immutable observation update unexpectedly succeeded'';\n  EXCEPTION WHEN SQLSTATE ''55000'' THEN\n    NULL;\n  END;\nEND;';

SELECT pass('Offer Finder foundation invariants hold');
SELECT * FROM finish();
ROLLBACK;
