export const passportProfileCopy={
 ru:{loading:'Загрузка…',error:'Не удалось загрузить данные',empty:'Пока нет событий',open:'Открыть',download:'Скачать',
  passport:{eyebrow:'Паспорт зрения',title:'Ваша история остаётся с вами',lead:'Проверки, направления и завершённая помощь — в одном защищённом месте.',next:'Следующий пересмотр',screenings:'История проверок',referrals:'Направления и помощь',recommendations:'Рекомендации',documents:'Документы клиники',routine:'Плановый контроль',review_recommended:'Рекомендуется обследование',urgent:'Срочное событие',created:'Создано',active:'Активна',completed:'Завершена',dismissed:'Скрыта',reviewAnnual:'Ежегодная проверка зрения',comfortBreaks:'Делайте регулярные перерывы',examFollowUp:'Пройдите рекомендованное обследование'},
  profile:{eyebrow:'Профиль',title:'Настройки и управление данными',personal:'Персональные данные',name:'Имя',phone:'Телефон',language:'Язык',region:'Регион',birthDate:'Дата рождения',notifications:'Уведомления',email:'Электронная почта',push:'Push-уведомления',program:'Программа работодателя',privacy:'Работодатель видит только обезличенные агрегаты, но не ваши ответы, результаты или документы.',access:'Согласия и доступ клиники',research:'Использование обезличенных данных для исследований',provider:'Клинический партнёр',grant:'Разрешить доступ',revoke:'Отозвать доступ',noProviders:'Нет доступных клинических партнёров',security:'Безопасность и активные устройства',current:'Текущее устройство',export:'Экспортировать мои данные',remove:'Запросить удаление данных',removeConfirm:'Создать запрос на удаление данных этой организации? После начала обработки отменить его будет нельзя.',cancelDeletion:'Отменить запрос',deletion:'Удаление данных',requested:'Запрос получен',processing:'Удаление выполняется',completed:'Данные удалены',cancelled:'Запрос отменён',failed:'Не удалось удалить данные',save:'Сохранить',saved:'Сохранено'}},
 en:{loading:'Loading…',error:'Could not load data',empty:'No events yet',open:'Open',download:'Download',
  passport:{eyebrow:'Vision passport',title:'Your history stays with you',lead:'Screenings, referrals and completed care in one protected place.',next:'Next review',screenings:'Screening history',referrals:'Referrals and care',recommendations:'Recommendations',documents:'Clinic documents',routine:'Routine review',review_recommended:'Exam recommended',urgent:'Urgent event',created:'Created',active:'Active',completed:'Completed',dismissed:'Dismissed',reviewAnnual:'Annual vision review',comfortBreaks:'Take regular visual breaks',examFollowUp:'Complete the recommended examination'},
  profile:{eyebrow:'Profile',title:'Settings and data controls',personal:'Personal details',name:'Name',phone:'Phone',language:'Language',region:'Region',birthDate:'Date of birth',notifications:'Notifications',email:'Email',push:'Push notifications',program:'Employer program',privacy:'Your employer sees anonymized aggregates only — never your answers, results or documents.',access:'Consents and clinic access',research:'Use anonymized data for research',provider:'Clinical partner',grant:'Grant access',revoke:'Revoke access',noProviders:'No clinical partners available',security:'Security and active devices',current:'Current device',export:'Export my data',remove:'Request data deletion',removeConfirm:'Create a request to delete data for this organization? It cannot be cancelled after processing starts.',cancelDeletion:'Cancel request',deletion:'Data deletion',requested:'Request received',processing:'Deletion in progress',completed:'Data deleted',cancelled:'Request cancelled',failed:'Data deletion failed',save:'Save',saved:'Saved'}}
} as const;

export const recommendationCopy={
 ru:{'review.annual':'Ежегодная проверка зрения','comfort.breaks':'Делайте регулярные перерывы','exam.follow_up':'Пройдите рекомендованное обследование'},
 en:{'review.annual':'Annual vision review','comfort.breaks':'Take regular visual breaks','exam.follow_up':'Complete the recommended examination'},
} as const;
