import { FormEvent,useEffect,useState } from 'react';
import { useLocation,useNavigate,useParams } from 'react-router-dom';
import { OpticalButton,OpticalCard,OpticalEyebrow,OpticalStatus } from '../../components/foundation/primitives';
import { useLanguage } from '../../contexts/LanguageContext';
import { cancelDataDeletion,exportEmployeeData,getDataDeletionStatus,getProfileSettings,requestDataDeletion,setConsent,updateProfileSettings } from './api';
import { passportProfileCopy } from './copy';
import type { DeletionStatus,ProfileSettings } from './types';

export function ProfilePage(){
 const {language}=useLanguage();const c=passportProfileCopy[language];const {organizationId=''}=useParams();const navigate=useNavigate();const location=useLocation();const [data,setData]=useState<ProfileSettings|null>(null);const [saveState,setSaveState]=useState<'idle'|'saving'|'saved'|'error'>('idle');const [actionError,setActionError]=useState(false);const [providerId,setProviderId]=useState('');
 useEffect(()=>{let active=true;void getProfileSettings(organizationId).then(v=>{if(active){setData(v);setProviderId(v.providers[0]?.id??'')}}).catch(()=>active&&setSaveState('error'));return()=>{active=false}},[organizationId]);
 async function runAction(action:()=>Promise<void>){setActionError(false);try{await action()}catch{setActionError(true)}}
 async function save(e:FormEvent){e.preventDefault();if(!data)return;setSaveState('saving');try{const updated=await updateProfileSettings(organizationId,{displayName:data.displayName,locale:data.locale,region:data.region,phone:data.phone,birthDate:data.birthDate,notificationEmail:data.notificationEmail,notificationPush:data.notificationPush});setData(updated);setSaveState('saved');if(updated.locale!==language){const pathname=location.pathname.replace(/^\/(ru|en)(?=\/)/,`/${updated.locale}`);navigate(`${pathname}${location.search}${location.hash}`,{replace:true})}}catch{setSaveState('error')}}
 async function consent(type:'research'|'clinic_access',granted:boolean,targetProvider:string|null=null){if(!data)return;await runAction(async()=>{await setConsent(organizationId,type,granted,targetProvider);setData(await getProfileSettings(organizationId))})}
 async function exportData(){await runAction(async()=>{const payload=await exportEmployeeData(organizationId);const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`vilu-data-${organizationId}.json`;link.click();URL.revokeObjectURL(url)})}
 async function removeData(){if(!confirm(c.profile.removeConfirm))return;await runAction(async()=>{const request=await requestDataDeletion(organizationId);if(data)setData({...data,deletionRequest:{id:request.id,status:request.status,requestedAt:request.requested_at,processedAt:request.processed_at}})})}
 async function cancelDeletion(){if(!data?.deletionRequest)return;await runAction(async()=>{const request=await cancelDataDeletion(organizationId,data.deletionRequest!.id);setData({...data,deletionRequest:{id:request.id,status:request.status,requestedAt:request.requested_at,processedAt:request.processed_at}})})}
 const deletionId=data?.deletionRequest?.id;const deletionStatus=data?.deletionRequest?.status;
 useEffect(()=>{if(!deletionId||!deletionStatus||!['requested','processing'].includes(deletionStatus))return;let active=true;const refresh=()=>{void getDataDeletionStatus(organizationId,deletionId).then(request=>{if(active)setData(value=>value?.deletionRequest?{...value,deletionRequest:{id:request.id,status:request.status,requestedAt:request.requestedAt,processedAt:request.processedAt}}:value)}).catch(()=>undefined)};refresh();const timer=window.setInterval(refresh,750);return()=>{active=false;window.clearInterval(timer)}},[deletionId,deletionStatus,organizationId]);
 if(!data)return <main className="employee-flow-shell">{saveState==='error'?c.error:c.loading}</main>;
 const research=data.consents.find(x=>x.type==='research')?.granted??false;const access=data.consents.filter(x=>x.type==='clinic_access'&&x.granted);const deletion=data.deletionRequest;
 return <main className="employee-flow-shell profile-page"><section className="employee-flow-hero"><div><OpticalEyebrow>{c.profile.eyebrow}</OpticalEyebrow><h1>{c.profile.title}</h1></div>{saveState==='saved'&&<OpticalStatus tone="success">{c.profile.saved}</OpticalStatus>}</section>
  <form onSubmit={save} className="profile-grid">
   <OpticalCard><h2>{c.profile.personal}</h2><label>{c.profile.name}<input value={data.displayName} onChange={e=>setData({...data,displayName:e.target.value})}/></label><label>{c.profile.phone}<input type="tel" value={data.phone??''} onChange={e=>setData({...data,phone:e.target.value})}/></label><label>{c.profile.birthDate}<input type="date" value={data.birthDate??''} onChange={e=>setData({...data,birthDate:e.target.value||null})}/></label><label>{c.profile.region}<input value={data.region??''} onChange={e=>setData({...data,region:e.target.value||null})}/></label><label>{c.profile.language}<select value={data.locale} onChange={e=>setData({...data,locale:e.target.value as 'ru'|'en'})}><option value="ru">Русский</option><option value="en">English</option></select></label></OpticalCard>
   <OpticalCard><h2>{c.profile.notifications}</h2><label className="profile-toggle"><span>{c.profile.email}</span><input type="checkbox" checked={data.notificationEmail} onChange={e=>setData({...data,notificationEmail:e.target.checked})}/></label><label className="profile-toggle"><span>{c.profile.push}</span><input type="checkbox" checked={data.notificationPush} onChange={e=>setData({...data,notificationPush:e.target.checked})}/></label></OpticalCard>
   <OpticalCard><h2>{c.profile.program}</h2><strong>{data.organizationName}</strong><p>{c.profile.privacy}</p></OpticalCard>
   <OpticalCard><h2>{c.profile.access}</h2><label className="profile-toggle"><span>{c.profile.research}</span><input type="checkbox" checked={research} onChange={e=>void consent('research',e.target.checked)}/></label><label>{c.profile.provider}<select value={providerId} onChange={e=>setProviderId(e.target.value)} disabled={!data.providers.length}>{data.providers.length?data.providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>):<option>{c.profile.noProviders}</option>}</select></label><OpticalButton disabled={!providerId||access.some(x=>x.providerOrganizationId===providerId)} onClick={()=>void consent('clinic_access',true,providerId)}>{c.profile.grant}</OpticalButton>{access.map(x=><div className="passport-row" key={x.providerOrganizationId}><span>{x.providerName}</span><button type="button" onClick={()=>void consent('clinic_access',false,x.providerOrganizationId)}>{c.profile.revoke}</button></div>)}</OpticalCard>
   <OpticalCard><h2>{c.profile.security}</h2>{data.devices.length?data.devices.map(d=><div className="passport-row" key={d.id}><strong>{d.label}</strong><span>{d.current?c.profile.current:new Intl.DateTimeFormat(language,{dateStyle:'short'}).format(new Date(d.lastSeenAt))}</span></div>):<p>{c.empty}</p>}</OpticalCard>
   <OpticalCard className="profile-danger"><h2>{c.profile.deletion}</h2><button type="button" onClick={()=>void exportData()}>{c.profile.export}</button>{deletion&&<p><OpticalStatus tone={deletion.status==='failed'?'warning':'neutral'}>{c.profile[deletion.status as DeletionStatus]}</OpticalStatus></p>}{deletion?.status==='requested'?<button type="button" onClick={()=>void cancelDeletion()}>{c.profile.cancelDeletion}</button>:deletion?.status==='completed'?null:<button type="button" disabled={deletion?.status==='processing'} onClick={()=>void removeData()}>{c.profile.remove}</button>}</OpticalCard>
   <OpticalButton disabled={saveState==='saving'} type="submit">{c.profile.save}</OpticalButton>{(saveState==='error'||actionError)&&<p role="alert">{c.error}</p>}
  </form>
 </main>;
}
