import {render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter,Route,Routes} from 'react-router-dom';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {LanguageProvider} from '../../../contexts/LanguageContext';
import {ProviderQueuePage} from '../ProviderQueuePage';

const api=vi.hoisted(()=>({getProviderQueue:vi.fn(),getProviderReferral:vi.fn(),bookAppointment:vi.fn(),escalateReferral:vi.fn(),confirmOutcome:vi.fn(),documentUrl:vi.fn()}));
vi.mock('../api',()=>api);
const item={id:'ref-1',priority:'urgent',status:'queued',respondBy:'2030-01-01T10:00:00Z',createdAt:'2030-01-01T09:00:00Z',patientName:'Ada',appointmentAt:null,documentsCount:1};
const detail={...item,version:3,appointment:null,documents:[{id:'doc-1',title:'Clinical note',type:'note',storagePath:'org/doc.pdf',issuedAt:'2030-01-01T09:00:00Z'}]};
function page(locale:'en'|'ru'='en'){localStorage.setItem('vilu_language',locale);return render(<LanguageProvider><MemoryRouter initialEntries={[`/${locale}/organizations/org-1/provider/queue`]}><Routes><Route path="/:locale/organizations/:organizationId/provider/queue" element={<ProviderQueuePage/>}/></Routes></MemoryRouter></LanguageProvider>)}
describe('ProviderQueuePage',()=>{beforeEach(()=>{vi.clearAllMocks();api.getProviderQueue.mockResolvedValue({items:[item],total:1});api.getProviderReferral.mockResolvedValue(detail);api.bookAppointment.mockResolvedValue(undefined)});
  it('shows loading instead of a false empty state',()=>{api.getProviderQueue.mockReturnValue(new Promise(()=>{}));page();expect(screen.getByText('Loading referrals…')).toBeInTheDocument();expect(screen.queryByText('No referrals match these filters.')).not.toBeInTheDocument()});
  it('blocks a duplicate booking and exposes the successful appointment',async()=>{const user=userEvent.setup();let finish!:()=>void;api.bookAppointment.mockReturnValue(new Promise<void>(resolve=>{finish=resolve}));api.getProviderReferral.mockResolvedValueOnce(detail).mockResolvedValueOnce({...detail,version:4,status:'appointment_booked',appointment:{id:'apt-1',scheduledAt:'2030-01-02T10:00:00Z',status:'booked',version:1}});page();await user.click(await screen.findByRole('button',{name:'Open record'}));const input=document.getElementById('appointment-at') as HTMLInputElement;await user.type(input,'2030-01-02T10:00');const button=screen.getByRole('button',{name:'Confirm booking'});await user.click(button);expect(screen.getByRole('button',{name:'Saving…'})).toBeDisabled();await user.click(screen.getByRole('button',{name:'Saving…'}));expect(api.bookAppointment).toHaveBeenCalledTimes(1);const requestKey=api.bookAppointment.mock.calls[0][4];expect(requestKey).toEqual(expect.any(String));finish();expect(await screen.findByRole('status')).toHaveTextContent('Appointment booked successfully.');expect(screen.getByText(/Scheduled for:/)).toBeInTheDocument()});
  it('opens a document window synchronously and localizes signed-url errors',async()=>{const user=userEvent.setup();const popup={opener:{},location:{href:''},close:vi.fn()};const open=vi.spyOn(window,'open').mockReturnValue(popup as unknown as Window);api.documentUrl.mockRejectedValue(new Error('expired'));page('ru');await user.click(await screen.findByRole('button',{name:'Открыть карточку'}));await user.click(screen.getByRole('button',{name:'Clinical note'}));expect(open).toHaveBeenCalledBefore(api.documentUrl);expect(await screen.findByRole('alert')).toHaveTextContent('Не удалось открыть документ');expect(popup.close).toHaveBeenCalled()});
  it.each([['en','Next'],['ru','Вперёд']] as const)('paginates the complete queue in %s',async(locale,nextLabel)=>{const user=userEvent.setup();api.getProviderQueue.mockResolvedValue({items:[item],total:51});page(locale);await user.click(await screen.findByRole('button',{name:nextLabel}));await waitFor(()=>expect(api.getProviderQueue).toHaveBeenLastCalledWith('org-1','','',50,50));expect(screen.getByText(locale==='ru'?'Страница 2 из 2':'Page 2 of 2')).toBeInTheDocument()});
  it('returns to the last valid page when the live queue shrinks',async()=>{const user=userEvent.setup();api.getProviderQueue.mockResolvedValueOnce({items:[item],total:51}).mockResolvedValueOnce({items:[],total:50}).mockResolvedValueOnce({items:[item],total:50});page();await user.click(await screen.findByRole('button',{name:'Next'}));await waitFor(()=>expect(api.getProviderQueue).toHaveBeenLastCalledWith('org-1','','',0,50));expect(await screen.findByText('Ada')).toBeInTheDocument();expect(screen.queryByText('No referrals match these filters.')).not.toBeInTheDocument()});
  it('ignores a late detail response after another patient is opened',async()=>{const user=userEvent.setup();const second={...item,id:'ref-2',patientName:'Bea'};let resolveFirst!:(value:typeof detail)=>void;api.getProviderQueue.mockResolvedValue({items:[item,second],total:2});api.getProviderReferral.mockImplementationOnce(()=>new Promise(resolve=>{resolveFirst=resolve})).mockResolvedValueOnce({...detail,id:'ref-2',patientName:'Bea'});page();const opens=await screen.findAllByRole('button',{name:'Open record'});await user.click(opens[0]);await user.click(opens[1]);const dialog=await screen.findByRole('dialog');expect(within(dialog).getByText('Bea')).toBeInTheDocument();resolveFirst(detail);await waitFor(()=>expect(within(dialog).queryByText('Ada')).not.toBeInTheDocument())});
  it('does not restore a closed patient after a late mutation refresh',async()=>{const user=userEvent.setup();let finish!:()=>void;api.escalateReferral.mockReturnValue(new Promise<void>(resolve=>{finish=resolve}));api.getProviderReferral.mockResolvedValueOnce(detail).mockResolvedValueOnce({...detail,status:'urgent_escalated'});page();await user.click(await screen.findByRole('button',{name:'Open record'}));await user.click(screen.getByRole('button',{name:'Escalate now'}));await user.click(screen.getByRole('button',{name:'Close'}));finish();await waitFor(()=>expect(api.getProviderReferral).toHaveBeenCalledTimes(2));expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(screen.queryByText('Referral escalated.')).not.toBeInTheDocument()});
  it('does not overwrite a newly opened patient with a late mutation refresh',async()=>{const user=userEvent.setup();const second={...item,id:'ref-2',patientName:'Bea'};let finish!:()=>void;api.escalateReferral.mockReturnValue(new Promise<void>(resolve=>{finish=resolve}));api.getProviderQueue.mockResolvedValue({items:[item,second],total:2});api.getProviderReferral.mockResolvedValueOnce(detail).mockResolvedValueOnce({...detail,id:'ref-2',patientName:'Bea'}).mockResolvedValueOnce({...detail,status:'urgent_escalated'});page();const opens=await screen.findAllByRole('button',{name:'Open record'});await user.click(opens[0]);await user.click(screen.getByRole('button',{name:'Escalate now'}));await user.click(opens[1]);expect(within(await screen.findByRole('dialog')).getByText('Bea')).toBeInTheDocument();finish();await waitFor(()=>expect(api.getProviderReferral).toHaveBeenCalledTimes(3));expect(within(screen.getByRole('dialog')).getByText('Bea')).toBeInTheDocument();expect(within(screen.getByRole('dialog')).queryByText('Ada')).not.toBeInTheDocument()});
  it('uses a separate idempotency key for the same action on another patient after failure',async()=>{const user=userEvent.setup();const second={...item,id:'ref-2',patientName:'Bea'};api.getProviderQueue.mockResolvedValue({items:[item,second],total:2});api.getProviderReferral.mockResolvedValueOnce(detail).mockResolvedValueOnce({...detail,id:'ref-2',patientName:'Bea'}).mockResolvedValueOnce({...detail,id:'ref-2',patientName:'Bea',status:'urgent_escalated'});api.escalateReferral.mockRejectedValueOnce(new Error('network')).mockResolvedValueOnce(undefined);page();const opens=await screen.findAllByRole('button',{name:'Open record'});await user.click(opens[0]);await user.click(screen.getByRole('button',{name:'Escalate now'}));expect(await screen.findByRole('alert')).toHaveTextContent('Action failed');const firstKey=api.escalateReferral.mock.calls[0][4];await user.click(screen.getByRole('button',{name:'Close'}));await user.click(opens[1]);await user.click(await screen.findByRole('button',{name:'Escalate now'}));await waitFor(()=>expect(api.escalateReferral).toHaveBeenCalledTimes(2));expect(api.escalateReferral.mock.calls[1][4]).not.toBe(firstKey);expect(await screen.findByRole('status')).toHaveTextContent('Referral escalated successfully.')});
  it('does not show a late mutation error after another patient is opened',async()=>{const user=userEvent.setup();const second={...item,id:'ref-2',patientName:'Bea'};let fail!:(reason?:unknown)=>void;api.getProviderQueue.mockResolvedValue({items:[item,second],total:2});api.getProviderReferral.mockResolvedValueOnce(detail).mockResolvedValueOnce({...detail,id:'ref-2',patientName:'Bea'});api.escalateReferral.mockReturnValue(new Promise<void>((_,reject)=>{fail=reject}));page();const opens=await screen.findAllByRole('button',{name:'Open record'});await user.click(opens[0]);await user.click(screen.getByRole('button',{name:'Escalate now'}));await user.click(opens[1]);expect(within(await screen.findByRole('dialog')).getByText('Bea')).toBeInTheDocument();fail(new Error('late failure'));await waitFor(()=>expect(screen.queryByRole('button',{name:'Saving…'})).not.toBeInTheDocument());expect(screen.queryByRole('alert')).not.toBeInTheDocument();expect(within(screen.getByRole('dialog')).getByText('Bea')).toBeInTheDocument()});
  it('allows outcome confirmation only after the scheduled appointment',async()=>{const user=userEvent.setup();api.getProviderReferral.mockResolvedValueOnce({...detail,status:'appointment_booked',appointment:{id:'future',scheduledAt:'2030-01-02T10:00:00Z',status:'booked',version:1}}).mockResolvedValueOnce({...detail,status:'appointment_booked',appointment:{id:'past',scheduledAt:'2020-01-02T10:00:00Z',status:'booked',version:1}});page();await user.click(await screen.findByRole('button',{name:'Open record'}));expect(screen.queryByRole('button',{name:'Confirm result'})).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Close'}));await user.click(screen.getByRole('button',{name:'Open record'}));expect(await screen.findByRole('button',{name:'Confirm result'})).toBeInTheDocument()});
  const states=[
    ['queued',true,true,false,false],
    ['appointment_booked',true,true,true,false],
    ['urgent_escalated',true,false,true,false],
    ['examination_completed',false,false,false,true],
    ['outcome_confirmed',false,false,false,true],
  ] as const;
  it.each(['en','ru'] as const)('shows only server-valid actions for every status in %s',async locale=>{
    const user=userEvent.setup();
    for(const [status,booking,escalation,outcome,closed] of states){
      api.getProviderReferral.mockResolvedValueOnce({...detail,status,appointment:['appointment_booked','urgent_escalated'].includes(status)?{id:'apt-1',scheduledAt:'2020-01-02T10:00:00Z',status:'booked',version:1}:null});
      const view=page(locale);
      await user.click(await screen.findByRole('button',{name:locale==='ru'?'Открыть карточку':'Open record'}));
      expect(screen.queryByRole('button',{name:locale==='ru'?'Подтвердить запись':'Confirm booking'})!==null).toBe(booking);
      expect(screen.queryByRole('button',{name:locale==='ru'?'Эскалировать сейчас':'Escalate now'})!==null).toBe(escalation);
      expect(screen.queryByRole('button',{name:locale==='ru'?'Подтвердить результат':'Confirm result'})!==null).toBe(outcome);
      expect(screen.queryByText(locale==='ru'?'Маршрут помощи завершён. Дополнительные клинические действия недоступны.':'This care loop is complete. No further clinical actions are available.')!==null).toBe(closed);
      view.unmount();
    }
  });
});
