export const eyeMapCopy = {
  ru: {
    eyebrow: 'Личная точка отсчета',
    title: 'Eye Map',
    intro:
      'Сделайте снимок области глаз и получите техническую карту качества и сопоставимости фотографии.',
    privacy:
      'Фото обрабатывается только в этой вкладке и не отправляется на сервер. Сохранить можно только технический результат без фотографии.',
    notMedical: 'Это визуальная, а не медицинская оценка.',
    startCamera: 'Открыть камеру',
    upload: 'Загрузить фото',
    uploadHint: 'JPEG, PNG или WebP',
    analyzing: 'Строим Eye Map...',
    analyzingDetail: 'Проверяем положение лица и видимость области глаз.',
    resultTitle: 'Ваш Eye Map готов',
    suitable: 'Снимок подходит для наблюдения',
    retake: 'Лучше переснять фотографию',
    retakeAction: 'Переснять',
    newPhoto: 'Другой снимок',
    showGuides: 'Показать ориентиры',
    hideGuides: 'Скрыть ориентиры',
    resultImageAlt: 'Фотография для локального анализа Eye Map',
    captureQuality: 'Качество снимка',
    alignment: 'Положение лица',
    visibility: 'Видимость области глаз',
    repeatability: 'Сопоставимость с вашей точкой отсчета',
    captureGood: 'Хорошее',
    captureAcceptable: 'Допустимое',
    captureRetake: 'Нужно переснять',
    aligned: 'Лицо расположено ровно',
    adjust: 'Есть небольшой наклон или смещение',
    bothEyes: 'Обе области глаз видны',
    baselineFirst: 'Это ваша первая точка отсчета',
    baselineFirstDetail:
      'Повторный снимок в похожих условиях позволит оценить техническую сопоставимость.',
    saveBaseline: 'Сохранить точку отсчета',
    saved: 'Сохранено только на этом устройстве',
    history: 'Личная история',
    historyEmpty: 'Сохраненных точек пока нет.',
    clear: 'Очистить историю',
    storageUnavailable: 'История недоступна в этом браузере.',
    demoTitle: 'Пример будущего сравнения с группой',
    demoBadge: 'Демонстрационные данные',
    demoBody:
      'Это макет будущего агрегированного сравнения при группе не менее 100 человек. Значения не рассчитаны по текущим пользователям и не относятся к вашему зрению.',
    demoAction: 'Когортное сравнение появится позже',
    back: 'Вернуться к трекеру',
    blocked: {
      no_face: 'Лицо не найдено. Расположите всё лицо в кадре.',
      multiple_faces: 'В кадре должен быть один человек.',
      pose: 'Смотрите прямо и держите телефон ровно.',
      distance: 'Измените расстояние: лицо должно занимать 40–60% кадра.',
      engine_unavailable: 'Не удалось выполнить локальный анализ.',
      unsupported_file: 'Выберите JPEG, PNG или WebP.',
    },
  },
  en: {
    eyebrow: 'Personal baseline',
    title: 'Eye Map',
    intro:
      'Capture the eye area and get a technical map of photo quality and comparability.',
    privacy:
      'The photo is processed only in this tab and is not sent to a server. Only the technical result can be saved, without the photo.',
    notMedical: 'This is a visual, not a medical assessment.',
    startCamera: 'Open camera',
    upload: 'Upload photo',
    uploadHint: 'JPEG, PNG or WebP',
    analyzing: 'Building your Eye Map...',
    analyzingDetail: 'Checking face position and eye-area visibility.',
    resultTitle: 'Your Eye Map is ready',
    suitable: 'This photo is suitable for observation',
    retake: 'It is better to retake the photo',
    retakeAction: 'Retake',
    newPhoto: 'Choose another photo',
    showGuides: 'Show landmarks',
    hideGuides: 'Hide landmarks',
    resultImageAlt: 'Photo used for local Eye Map analysis',
    captureQuality: 'Photo quality',
    alignment: 'Face position',
    visibility: 'Eye-area visibility',
    repeatability: 'Comparability with your baseline',
    captureGood: 'Good',
    captureAcceptable: 'Acceptable',
    captureRetake: 'Retake needed',
    aligned: 'Face position is aligned',
    adjust: 'Slight tilt or offset detected',
    bothEyes: 'Both eye areas are visible',
    baselineFirst: 'This is your first baseline',
    baselineFirstDetail:
      'A repeat photo in similar conditions can show technical comparability.',
    saveBaseline: 'Save baseline',
    saved: 'Saved only on this device',
    history: 'Personal history',
    historyEmpty: 'No saved baselines yet.',
    clear: 'Clear history',
    storageUnavailable: 'History is unavailable in this browser.',
    demoTitle: 'Preview of a future group comparison',
    demoBadge: 'Demonstration data',
    demoBody:
      'This previews a future aggregate comparison for groups of at least 100 people. Values are not calculated from current users and do not describe your vision.',
    demoAction: 'Cohort comparison is coming later',
    back: 'Back to Vision Tracker',
    blocked: {
      no_face: 'No face found. Keep your whole face in the frame.',
      multiple_faces: 'Only one person should be in the frame.',
      pose: 'Look straight ahead and hold the phone level.',
      distance: 'Adjust distance so your face fills 40–60% of the frame.',
      engine_unavailable: 'Local analysis could not be completed.',
      unsupported_file: 'Choose a JPEG, PNG or WebP file.',
    },
  },
} as const;
